#!/usr/bin/env sh

(cd Balloon && ./build "$@")
(cd Bouncy && ./build "$@")
(cd Card && ./build "$@")
(cd Demo && ./build "$@")
(cd Primes && ./build "$@")
(cd Rick && ./build "$@")
(cd Splinter && ./build "$@")
