name: Build

on:
  - push

jobs:
  main:
    runs-on: ubuntu-latest
    container: jamieleecho/coco-dev:0.38
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./build-github
